### ISSUE TITLE
【Swift Package Manager】 error: The project doesn't contain a .pbxproj file at path: /Users/apple/Desktop/Demo/ObjectBoxDemo/ObjectBoxDemo.xcodeproj

### ISSUE THREAD

**Issue by coderliu007** [objectbox/objectbox-swift#82] opened 2023-09-27 10:47 UTC
**Describe the bug**
After executing setup.rb, an error occurs when compiling the project

note: using module name ObjectBoxDemo
error: The project doesn't contain a .pbxproj file at path: /Users/apple/Desktop/Demo/ObjectBoxDemo/ObjectBoxDemo.xcodeproj

**Basic info (please complete the following information):**
 - ObjectBox version (are you using the latest version?): [e.g. 1.9.0]
 - Reproducibility: [always]
 - Device:  iPhone 15
 - OS:  iOS 17
 - Xcode: xcode15.0

![Snip20230927_18](https://github.com/objectbox/objectbox-swift/assets/83936591/640b821b-303c-4143-b29b-494bb0d446f3)

**Comment by greenrobot-team** [comment] 2023-10-09 12:04
Thanks! As said in #19, there is no official support for Swift Package Manager, yet. But we'll have a look when we next try to add SPM support.

**Comment by jonasrotilli** [comment] 2024-01-07 21:13
Hi, I have a project that uses Object Box, after updating XCode I am receiving this same error.

`Cannot find Sourcery in the expected location at '/Users/jonasrotilli/Documents/iOS/upCampo/Pods/ObjectBox/Mac/OBXCodeGen.framework/Versions/A/Resources/Sourcery.app/Contents/MacOS/Sourcery'`

From what you said, this is related to Swift Package Manager.

But after all, what can I do to make it work in my project? Is there any way to disable it?
Any help is welcome, I need to release a fix and I can't compile the project.

**Comment by greenrobot-team** [comment] 2024-07-27 04:31
Closing this as duplicate of #19.

**Closed by greenrobot-team** 2024-07-27 04:31 UTC
Labels: bug
