### ISSUE TITLE
ios平台 有人对比过wcdb么？ 哪个速度最快？

### ISSUE THREAD

**Issue by NBXXF** [objectbox/objectbox-swift#80] opened 2023-05-04 06:06 UTC
:rotating_light: First, please check:
 - existing issues,
 - Docs https://swift.objectbox.io/
 - FAQ page https://swift.objectbox.io/faq

Start with a clear and concise description of what problem you are trying to solve.
Often there is already a solution! 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context (e.g. platform or language) about the feature request here.

**Comment by greenrobot-team** [comment] 2023-05-08 06:22
Duplicate of #79.

Also see my comment at https://github.com/objectbox/objectbox-swift/issues/79#issuecomment-1537818895.

**Closed by greenrobot-team** 2023-05-08 06:22 UTC
Labels: enhancement
